version: '3.9'

services:
  mariadb:
    image: mariadb:10.9.2
    container_name: mariadb
    environment: 
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=1234
      - MARIADB_DATABASE=go_todo
    ports: 
      - 3306:3306
    volumes: 
      - ./.docker/mariadb:/var/lib/mysql
    networks:
      - goweb
  
  app:
    depends_on:
      - mariadb
    container_name: go-todo
    environment: 
      - MYSQL_HOST=mariadb
      - APP_HOST=
    build: .
    restart: always
    ports:
      - 1112:3000
    entrypoint: ["/app/wait-for.sh", "mariadb:3306", "--", "/app/start.sh"]
    command: ["/app/main"]
    networks:
      - goweb

networks:
  goweb:
    driver: bridge
